name: Build and Depoly dev management 
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: list env
        run: env

      - name: docker build management
        run: docker build -f management/web/Dockerfile -t docker.pkg.github.com/${GITHUB_REPOSITORY}/management:action-${GITHUB_REF##*/}-ci-${GITHUB_RUN_NUMBER} -t docker.pkg.github.com/${GITHUB_REPOSITORY}/management:action-ci management/web

      - name: docker images 
        run: docker images

      - name: docker login
        run : docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY%/*} -p ${{ secrets.packages_token }}

      - name: docker push management tag branch number
        run : docker push docker.pkg.github.com/${GITHUB_REPOSITORY}/management:action-${GITHUB_REF##*/}-ci-${GITHUB_RUN_NUMBER}
      
      - name: docker push management tag latest
        run: docker push docker.pkg.github.com/${GITHUB_REPOSITORY}/management:action-ci

  deploy-dev:
     needs: build
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2

       - name: list env
         run: env && ls

       - name: replace project name
         run: sed -i "s|docker.pkg.github.com\/idcf-boat-house\/boat-house|docker.pkg.github.com\/${GITHUB_REPOSITORY%/*}\/boat-house|g" kompose/test/management-*.yaml

       - name: replace docker images tags
         run: sed -i "s|:latest$|:action-ci|g" kompose/test/management-*.yaml

       - name: grep images url
         run: grep -i "image:" kompose/test/management-*.yaml
         #run: ls kompose/test/management-*.yaml

       - uses: Azure/k8s-set-context@v1
         with:
           kubeconfig: ${{ secrets.KUBE_CONFIG }}

       - uses: Azure/k8s-create-secret@v1
         with:
           container-registry-url: docker.pkg.github.com
           container-registry-username: ${GITHUB_REPOSITORY%/*}
           container-registry-password: ${{ secrets.packages_token }}
           secret-name: demo-k8s-secret

       - uses: Azure/k8s-deploy@v1
         with:
           namespace: 'boathouse-test-github'
           manifests: |
              kompose/test/management-deployment.yaml
              kompose/test/management-svc.yaml
           kubectl-version: 'latest'
